### PR TITLE
[WICKET-6648] initiate and onBeforeDownload signatures are changed

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by martin-g** [comment]
How much effort is to add an example usage with WebSockets to wicket-examples > WebSockets demo ?

**Comment by solomax** [comment]
I'll add, should be easy :)

**Comment by solomax** [comment]
@martin-g it seems `mvn jetty:run` is not working in `wicket-examples`, 
how are you running it for quick tests?

**Comment by solomax** [comment]
`mvn jetty:run-exploded` seems to work :)

**Comment by martin-g** [comment]
I use `StartExamples#main()` in the IDE. It is much easier to debug and use HotSwap code replace (no need to restart, especially with DCEVM).

**Comment by solomax** [comment]
Is it OK to merge this PR?

**Pull request merged**
