### PR TITLE
Error page redirection support for autocomplete ajax response

### PR DESCRIPTION
**Pull request by iamrakesh**
Autocomplete field resulting an exception with 
org.apache.wicket.settings.ExceptionSettings#errorHandlingStrategyDuringAjaxRequests, 
set to 
org.apache.wicket.settings.ExceptionSettings.AjaxErrorStrategy.REDIRECT_TO_ERROR_PAGE

does not redirect to the error page.

This fix will enable page redirection even for autocomplete field.

### CODE REVIEW

**Comment by iamrakesh** [comment]
Not sure about JavaScript test added, as I see all tests (part of all.html) go green always.

**Comment by martin-g** [comment]
wicket-core/src/test/js/** cover only the .js files in -core.
There are no *unit* JS tests for -extensions module.
In https://github.com/apache/wicket/tree/master/wicket-examples/src/main/webapp/js-test there are *functional* tests though for some of the examples. There is no such for the autocomplete example yet.

**Comment by martin-g** [comment]
Please create a ticket in JIRA with a quickstart for the problem in autocomplete.
I just checked the diff and I see that you actually modified wicket-ajax-jquery.js, not wicket-autocomplete.js. Changes here need more attention before applying!

**Comment by iamrakesh** [comment]
Yes, changes to wicket-ajax-jquery.js need more attention, created a ticket for it with description
https://issues.apache.org/jira/browse/WICKET-6075

**Comment by solomax** [comment]
This PR seems to be inactive for too long :(
I guess it can be dropped? :)

**Pull request closed without merging**
