### PR TITLE
Update Application_cs.properties

### PR DESCRIPTION
**Pull request by vrozkovec**
Replace incorrect "greater than" with "at least"

### CODE REVIEW

**Review by reiern70 — APPROVED** [review]
Approving this is an act of faith :-)

**Comment by solomax** [comment]
I would convert this file to XML format, so edit would be less painful :))

**Review by martin-g — APPROVED** [review]

**Review by solomax — APPROVED** [review]

**Comment by martin-g** [comment]
> Approving this is an act of faith :-)

One could use https://examples9x.wicket.apache.org/unicodeconverter/ to see the real letters.

**Comment by martin-g** [comment]
Do we need a JIRA ticket too ?
The changes are really small, so I am OK without ticket.

**Comment by vrozkovec** [comment]
I can convert the file to Application_cs.utf8.properties, should I make another PR? Or is there a reason why you keep using encoded version of .properties?
If needed/wanted, I could convert all .properties to .utf8.properties.

**Comment by martin-g** [comment]
+1 to convert all .properties to .utf8.properties !
But please create a ticket in JIRA for the changelog!

**Comment by vrozkovec** [comment]
Created: https://issues.apache.org/jira/browse/WICKET-7063
In what branch should I do the change? Will you cherry-pick it to other branches? 
And should I also rename all files to contain .utf8. in the filename, even if there are no encoded entities in the file, so it is future-proof?

**Comment by martin-g** [comment]
> In what branch should I do the change?

`master`

> Will you cherry-pick it to other branches?

If requested - yes!


> And should I also rename all files to contain .utf8. in the filename, even if there are no encoded entities in the file, so it is future-proof?

Yes, please!

**Comment by vrozkovec** [comment]
@martin-g done: #596 
PR #596 contain also identical factual fix of Czech `RangeValidator.minimum` resource key as this PR.

**Comment by martin-g** [comment]
Fixed with #596

**Pull request closed without merging**
