### PR TITLE
WICKET-7103

### PR DESCRIPTION
**Pull request by renoth**
see https://issues.apache.org/jira/browse/WICKET-7103

### CODE REVIEW

**Review by solomax — APPROVED** [review]
LGTM

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Please rebase your branch to latest wicket:master.
I could do it too but I don't want to force-push to your master...

**Comment by martin-g** [comment]
```

org.apache.wicket.util.license.JavaLicenseHeaderHandler failed. The following files(1) didn't have correct license header:
NONE /home/runner/work/wicket/wicket/wicket-extensions/src/test/java/org/apache/wicket/extensions/ajax/markup/html/modal/ModalDialogTest.java
```

**Comment by renoth** [comment]
sorry forgot the license, should work now :)

**Pull request merged**
