### PR TITLE
Convert wicket ajax to typescript

### PR DESCRIPTION
**Pull request by andruhon**
Continuing discussion about converting wicket-ajax-jquery.js into TypeScript.

Finally I reached the stage when all tests passing and I can run ajax section in wicket examples, so I decided to create a proper PR to continue discussion.

I created some utility objects as "modules" which which means they may not be mutated on runtime (transpiled with Object.freeze):
Wicket.Class
Wicket.DOM
Wicket.Xml
Wicket.Form
Wicket.Head
Wicket.Head.Contributor

I'm not sure if it's correct, please let me know if you think that these modules should be converted into classes with static methods or simply into JS objects.

### CODE REVIEW

**Comment by martin-g** [comment]
I am +1 to make these changes!
But we should apply the changes from https://github.com/apache/wicket/pull/359

**Comment by andruhon** [comment]
Another important point to discuss is a format. The IIFE is currently configured is good to make it compatible with Wicket 8 stuff. Essentially what I have here _supposed_ to be a drop in replacement of existing wicket-modal-jquery, and could potentially be backported to Wicket 8. 

I think for future Wicket releases we can consider other options such as AMD, UMD or CommonJS, or make to have a few JS files built in and allow end developers to pick whichever is more convenient for them.

**Comment by martin-g** [comment]
> I think for future Wicket releases we can consider other options such as AMD, UMD or CommonJS

I do not see a reason for this. No one ever asked for any of those. Let's not over-engineer it for no reason.

P.S. ... and I believe the future is in ESM. Even Node.js added support for it in v12

**Comment by andruhon** [comment]
It seems to work pretty well. Should I continue and try adding a WICKET-6667 #359 into this one?

**Comment by martin-g** [comment]
I am +1 but others didn't give their opinion yet.
Let's discuss at dev@ first before wasting your time.

**Comment by andruhon** [comment]
> dev@

@martin-g do you refer to the dev@wicket.apache.org mail list?

**Comment by ivaynberg** [comment]
i am +1 on this as long as it is committed in such a way that git log --follow will stick pick up the history of the old js files..

**Comment by andreikondratev** [comment]
@ivaynberg It's achevable. 

I can do it with moving and merging back which will lead to a bunch of commits for each ts file in the history. Please let me know if you think it's going to be a problem or you know a better way.
```
Split history wicket-ajax-jquery.js to Event.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Event.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Event.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Event.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Ajax.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Ajax.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Ajax.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Ajax.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Wicket.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Wicket.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Wicket.ts Andrew Kondratev 17/05/2019 14:33
Split history wicket-ajax-jquery.js to Wicket.ts Andrew Kondratev 17/05/2019 14:33
```

**Comment by martin-g** [comment]
> @martin-g do you refer to the [dev@wicket.apache.org](mailto:dev@wicket.apache.org) mail list?

Yes.

**Comment by andruhon** [comment]
Closing this PR because it has been decided to not proceed with these changes. 
A permalink to mail list discussion as a reference.
https://lists.apache.org/thread.html/0b5b1fff59b1a448987c1da7f5a91e8942a6cd4ef2386674e7505df8@%3Cdev.wicket.apache.org%3E

**Pull request closed without merging**
