### PR TITLE
WICKET-6289 fix autolinker so it does not generate an onclick attribu…

### PR DESCRIPTION
**Pull request by duesenklipper**
…te for img tags

### CODE REVIEW

**Comment by martin-g** [comment]
Is it really needed for 1.5.x ?
This branch is for security fixes only.

**Comment by duesenklipper** [comment]
It's not really needed for 1.5, no. I just first came across it in 1.5 while helping a customer migrate a whole bunch of applications from 1.4 - currently on the way to 7.x. I don't mind this not getting in, it would simply be convenient for this.

**Comment by martin-g** [comment]
@duesenklipper Please close this PR! Thanks!

**Comment by martin-g** [comment]
@duesenklipper Ping!

**Pull request closed without merging**
