### PR TITLE
[WICKET-6783] ConcurrentHashSet is removed

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by bitstorm** [comment]
Looks good to me!

**Comment by solomax** [comment]
@bitstorm this should be added to "Migration guide", I guess, but I was unable to find it :((
this https://cwiki.apache.org/confluence/display/WICKET#Index-Migrations seems to be the old place :((

**Comment by martin-g** [comment]
https://cwiki.apache.org/confluence/display/WICKET/Migration+to+Wicket+9.0

**Comment by solomax** [comment]
@martin-g  It seems I don't have permission to edit this page :(

**Comment by martin-g** [comment]
Access granted!

**Pull request merged**
