### PR TITLE
[WICKET-7037] add SameSite attribute to download finished cookie

### PR DESCRIPTION
**Pull request by reiern70**

### CODE REVIEW

**Comment by solomax** [comment]
@reiern70 Would it be possible to add XML configuration (like `wicket.mode`) ?

**Comment by reiern70** [comment]
> @reiern70 Would it be possible to add XML configuration (like `wicket.mode`) ?



> 



> @reiern70 Would it be possible to add XML configuration (like `wicket.mode`) ?

Not following you... You meam something like

image

**Comment by reiern70** [comment]
> Yes, exactly so this settings can be set without code modification and recompilation :)

Shall this be part of some application settings?

**Review by martin-g — APPROVED** [review]

**Comment by solomax** [comment]
> Shall this be part of some application settings?

In our case init parameter of servlet context will be enough :))

**Comment by martin-g** [comment]
> In our case init parameter of servlet context will be enough :))

If Wicket won't set this value into some **Settings bean then there is nothing to do here. The application can set the extra init-param in its web.xml/annotation and read it from the ServletContext.

**Comment by reiern70** [comment]
> > In our case init parameter of servlet context will be enough :))
> 
> If Wicket won't set this value into some **Settings bean then there is nothing to do here. The application can set the extra init-param in its web.xml/annotation and read it from the ServletContext.

Yes... but then for all the AjaxDonwloadBehaviors you will need to:

1. Read this parameter 
2. Adapt your code to do `ajaxDonwloadBehavior.setAttribute("SameSite", "What you read from parameter");

@solomax 

You can allways roll you own AjaxDonwloadBehavior and do

```
class MyAjaxDonwloadBehavior extends AjaxDonwloadBehavior {

     MyAjaxDonwloadBehavior(IResource resource) {
       super (resource);
       setSameSite("read it from somewhere");
     }
}
```

But I stilll see the value of fixing some site without tocuhing your code (mind that for wicket 9.x you still will need to configure application server to decorate cookies).

**Comment by reiern70** [comment]
@martin-g Should I add such configuration option?

**Comment by reiern70** [comment]
> > You can allways roll you own AjaxDonwloadBehavior and do
> 
> Good point! Thanks :)

But I still see a valid use case for what you requested for existing applications:

1- You have browser warnings
2- You upgrade wicket + add some new system property to "your deployment"
3- redeploy and warnings are gone 

If this metits to have more configuration I don't know.

**Comment by solomax** [comment]
Yes, this would be ideal
But Custom AjaxDownloadBehavior is something we can workaround with until Wicket-10 :)

**Comment by reiern70** [comment]
> Yes, this would be ideal But Custom AjaxDownloadBehavior is something we can workaround with until Wicket-10 :)

For 9.x we need

https://github.com/apache/wicket/pull/566

**Pull request merged**
