### PR TITLE
WICKET-6886 LambdaChoiceRenderer with unit tests

### PR DESCRIPTION
**Pull request by rkurucz9**
I would like to add a LambdaChoiceRenderer that is based on SerializableFunction.

### CODE REVIEW

**Comment by rkurucz9** [comment]
Please close my pull request, if you approved or rejected it.

**Comment by rkurucz9** [comment]
My feature request was merged into the apache:wicket codebase.
You can see it in the https://issues.apache.org/jira/browse/WICKET-6886 issue.

**Comment by svenmeier** [comment]
Many thanks!

**Comment by rkurucz9** [comment]
You're welcome. :)

**Pull request closed without merging**
