### PR TITLE
Make DateLabel implement IGenericComponent<Date>, since it only allows I...

### PR DESCRIPTION
**Pull request by tkruse**
...Model<Date>

### CODE REVIEW

**Comment by svenmeier** [comment]
Thanks.

**Comment by klopfdreh** [comment]
This PR can be closed due to https://github.com/apache/wicket/commit/ad11f1277684165e64759b10d3c14c40cbe2e79d

Thank you @tkruse

**Comment by martin-g** [comment]
@tkruse Ping!
Please close this PR because we don't have the permissions to do it. Thank you!

**Comment by tkruse** [comment]
closing as requested.

**Pull request closed without merging**
