### PR TITLE
[WICKET-7025] package private methods are intercepted by ByteBuddy

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Review by martin-g — CHANGES_REQUESTED** [review]
Please add/update a test case.

**Review by martin-g — APPROVED** [review]

**Comment by solomax** [comment]
@martin-g shall I cherry-pick this code to wicket-9?

**Comment by martin-g** [comment]
Yes, I think it is a good idea!

**Comment by solomax** [comment]
Done, thanks! :)

**Comment by bitstorm** [comment]
@solomax thank you!

**Pull request merged**
