### PR TITLE
Improve formatting of example snippet

### PR DESCRIPTION
**Pull request by jmewes**

### CODE REVIEW

**Comment by jmewes** [comment]
Currently this snippet is hardly readable in the documentation:

before

With this commit is should become better:

after_png

**Comment by bitstorm** [comment]
thank you @jmewes !

**Comment by paulbors** [comment]
Should we not consider a code style machine cleanup for the entire project?

**Comment by martin-g** [comment]
@paulbors Any improvements are very welcome!

**Comment by solomax** [comment]
I would not change `tab` with 2 spaces for whole project
Even this markup can have `tab` and will be readable if CSS will be in separate file

my 2c

**Comment by martin-g** [comment]
Hi @paulbors ,

I am not sure this is a good idea. There is no big of a problem with the current formatting. Such big re-formattings usually lead to problems later with merging/cherry-picking commits from one branch to the other.

**Comment by paulbors** [comment]
I tend to agree as this proj is widely used and a bug can easily creep in even with the extensive test coverage. If it wasn't as popular it would have made more sense. The kind of good problems to have :)

However, the question still remains: should the comitee vote on adopting a single uniform code style and enforce it going forward? Over time the code base can be refactored to catch up.

**Pull request closed without merging**
