### PR TITLE
JavascriptReferenceType: Implement Serializable

### PR DESCRIPTION
**Pull request by leccyril**
Implement classes newly added as Serializable to be able to store in cache or to be serialized.

Fix https://issues.apache.org/jira/projects/WICKET/issues/WICKET-7076?filter=allissues

### CODE REVIEW

**Review by theigl — APPROVED** [review]
LGTM.

@martin-g: Do you know when we use `IClusterable` vs `Serializable`? Does it matter?

**Comment by martin-g** [comment]
IClusterable was introduced so that cache providers, like [Terracotta](https://www.terracotta.org/), could decide what is Wicket specific and what is generic-Serializable.
For consistency with the other Wicket classes I'd prefer to use `IClusterable` here too.

**Comment by leccyril** [comment]
Hi,

Yes it makes sense

Youre al right



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Martin Grigorov ***@***.***>
Date : 27/09/2023 12:50 (GMT+04:00)
À : apache/wicket ***@***.***>
Cc : leccyril ***@***.***>, Author ***@***.***>
Objet : Re: [apache/wicket] JavascriptReferenceType: Implement Serializable (PR #664)


IClusterable was introduced so that cache providers, like Terracotta<https://www.terracotta.org/>, could decide what is Wicket specific and what is generic-Serializable.
For consistency with the other Wicket classes I'd prefer to use IClusterable here too.

**Comment by leccyril** [comment]
you want i change or you will do it ?
thanks !

**Comment by theigl** [comment]
Please make the change @leccyril.

**Comment by leccyril** [comment]
done

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you, @leccyril !

**Pull request merged**
