### PR TITLE
 Add hook method for exception handling to StatelessChecker

### PR DESCRIPTION
**Pull request by kemsakurai**
I used StatelessChecker from wicket-devutils, It is verifying whether it is StatelessPage or not.
Currently, when it is not StatelessPage, StatelessChecker throw exceptions always.
I logged an error and thought there was a use case I would like to check later.
I implemented a hook method based on #205  feedback.

### CODE REVIEW

**Comment by martin-g** [comment]
Do you really need all those `#failXYZ()` methods ?
One isn't enough ?

**Comment by kemsakurai** [comment]
In my use case, one `fail` method is enough.

However, in the current implementation, for components with stateful behavior, IllegalStateException is thrown.
I did not change this part.
Therefore, I created a `fail` method for each component.

To make one `fail` method,
Can I change IllegalStateException to IllegalArgmentException?

**Comment by svenmeier** [comment]
Neither IllegalStateException nor IllegalArgumentException seems right to me. Probably it's better to just throw WicketRuntimeException.

**Comment by martin-g** [comment]
`IllegalStateException` looks good to me. The developer expects that the page is in stateless state but it is not!
What about introducing a custom exception and pass it to the `#fail()` method ? By default it will be thrown but the application can override the method and log it or do whatever it finds suitable.

`if (!condition) { fail(new CustomException("A good message")) }`
and 
````java
protected void fail(CustomException cx) {
  throw cx;
}
```
or 
````java
protected void fail(CustomException cx) {
  LOG.warn("The page is not really stateful: {}", cx.getMessage(), cx);
}
```

**Comment by kemsakurai** [comment]
Thanks for the suggestion.
I think you can create a `StatelessCheckFailureException` that inherits from WicketRunTimeException  
and let StateFullChecker throw a StatelessCheckFailureException.
I will try implementing it again.
This pull request is closed. 
Thanks.

**Pull request closed without merging**
