### PR TITLE
[WICKET-7068] Tree styles are updated to be RTL-friendly

### PR DESCRIPTION
**Pull request by solomax**
This one can be tested at https://examples9x.wicket.apache.org/tree by setting `dir="rtl"` attribute for `<html>` tag

I'll create JIRA if this PR will be considered useful :)

### CODE REVIEW

**Comment by reiern70** [comment]
@solomax Maybe create a second example page with dir="rtl"

**Comment by solomax** [comment]
I'm not sure what would be the best way in this case :(

It might be some sort of dropdown (so every page can be checked in RTL), but this might be useless due to all contents is in English ....

**Review by martin-g — APPROVED** [review]
It looks OK to me but I am not the best person to review CSS code!

**Comment by martin-g** [comment]
@solomax Should this be ported to `master` ?

**Comment by solomax** [comment]
> @solomax Should this be ported to `master` ?

Unfortunately while cherry-picking and testing I found minified CSS is broken :(

please see https://github.com/apache/wicket/pull/602

This one should be additionally fixed by merging #602 or reverted .... :((

**Pull request merged**
