### PR TITLE
Fix condition for simple top level navigation

### PR DESCRIPTION
**Pull request by papegaaij**

### CODE REVIEW

**Review by martin-g — COMMENTED** [review]
Do we want to add some unit tests ?

**Comment by papegaaij** [comment]
@martin-g The tests were already supposed to check this behavior, however WicketTester defaults to POST, which caused it not to trigger the error. I've updated the tests to use GET. Also, the test that was supposed to check the top level navigation did not trigger that specific code, because it used an incorrect sec-fetch-site header.

**Review by martin-g — APPROVED** [review]
Looks better now!
Maybe we should add a new test for `POST` too ?

**Comment by papegaaij** [comment]
> Maybe we should add a new test for POST too ?
Yes, good idea. I've added the test.

**Pull request merged**
