### PR TITLE
Add more modal customizations

### PR DESCRIPTION
**Pull request by andruhon**
More Modal settings as promised in discussion of #294 . Sorry it took longer than I expected, was buried in work.

### CODE REVIEW

**Comment by martin-g** [comment]
For completeness just to mention that these settings could be set by overriding `ModalWindow#postProcessSettings(JSONObject settings)`

**Comment by andreikondratev** [comment]
Hi! Is this change got stuck? Should I do anything to proceed?

**Comment by martin-g** [comment]
I will create a ticket in JIRA for this PR and merge it.

**Comment by martin-g** [comment]
https://issues.apache.org/jira/browse/WICKET-6640

**Comment by martin-g** [comment]
Thank you, @andruhon !

**Comment by andreikondratev** [comment]
Should I next time create a jira ticket for change like this?

**Comment by solomax** [comment]
@andreikondratev JIRA tickets helps to create release notes
So, I believe, it will speed up things

**Comment by martin-g** [comment]
Yes, most users don't read the git commit history to see what's new in a release. Wicket distributions (.tar.gz and .zip) contain RELEASE_NOTES file with the export from JIRA.

GitHub releases (actually Git tags) are not official Apache releases.

**Pull request merged**
