### PR TITLE
WICKET-7034: Publish WebSocket events even if connection was already …

### PR DESCRIPTION
**Pull request by dstoch**
This PR contains fix for WICKET-7034

### CODE REVIEW

**Comment by martin-g** [comment]
Thank you, @dstoch !

**Comment by dstoch** [comment]
This PR is for wicket-9.x. I am not sure how to fix this in master (10.x)? Should I prepare another PR or it will be merged other way?

**Comment by martin-g** [comment]
I have already cherry-picked it with https://github.com/apache/wicket/commit/f3e40820c8d459cf668e059f55c76dc4b73e3732

**Comment by martin-g** [comment]
Oops! I pushed it to a wrong branch!

**Comment by martin-g** [comment]
https://github.com/apache/wicket/commit/9fa35bbc5403f94a62c73bcb83b525a9a606429f

**Comment by dstoch** [comment]
Ok, thank you @martin-g.

**Pull request merged**
