### PR TITLE
WICKET-7093: Adding "form-action" to the CSP Directives

### PR DESCRIPTION
**Pull request by kaczorek89**
Add support for missing CSP directives [https://issues.apache.org/jira/browse/WICKET-7093](url)

### CODE REVIEW

**Comment by solomax** [comment]
Hello @kaczorek89 your PR seems to be against `wicket-9.x`, please change target branch :)

**Comment by solomax** [comment]
@kaczorek89 could you please create JIRA here: https://issues.apache.org/jira/projects/WICKET

And add it to PR title? (so we will have it in CHANGELOG :)))

**Review by solomax — APPROVED** [review]

**Comment by papegaaij** [comment]
@solomax the JIRA issue was already created by Martin: https://issues.apache.org/jira/browse/WICKET-7093

**Comment by solomax** [comment]
> @solomax the JIRA issue was already created by Martin: https://issues.apache.org/jira/browse/WICKET-7093

By bad, missed it in the description :(
Sorry for the noise

**Comment by martin-g** [comment]
Thank you, @kaczorek89 !

**Pull request merged**
