### PR TITLE
[WICKET-6647] Upgrade asm to 7.1 in master

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by solomax** [comment]
@mattrpav I got build error with this change:
```
WARNING] 
Dependency convergence error for org.ow2.asm:asm:7.0 paths to dependency are:
+-org.apache.wicket:wicket-ioc:9.0.0-SNAPSHOT
  +-cglib:cglib:3.2.10
    +-org.ow2.asm:asm:7.0
and
+-org.apache.wicket:wicket-ioc:9.0.0-SNAPSHOT
  +-org.ow2.asm:asm-util:7.1
    +-org.ow2.asm:asm:7.1
and
+-org.apache.wicket:wicket-ioc:9.0.0-SNAPSHOT
  +-org.ow2.asm:asm-util:7.1
    +-org.ow2.asm:asm-tree:7.1
      +-org.ow2.asm:asm:7.1

icket-ioc: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed
```

I'm afraid some additional changes are required

BTW can you close #350, I'll cherry-pick this one into wicket-8.x ....

**Comment by mattrpav** [comment]
@solomax apologies for the build warn. I created this PR to see if there was some CI/CD tied to Wicket's PR's. This is a simple fix to exclude asm requested by cglib. I need to upgrade my local JDK and will re-test. Thanks

**Comment by mattrpav** [comment]
@solomax what is the preferred workflow for patches?

**Comment by solomax** [comment]
@mattrpav  PR with the link to JIRA is perfectly fine :)
You did everything right :)

**Comment by mattrpav** [comment]
There is a cglib-nodep that wicket-ioc could depend on, and then inherit the asm dependency (which is used by other wicket modules).

Q: This seems to be a driver's choice option here-- is there a strong preference to stay tightly coupled to cglib's transitive dependency on asm, or would the cglib-nodep approach be useful?

**Comment by solomax** [comment]
I would say `cglib-nodep` is better option since we have `asm` as separate dependency ...
@martin-g, @svenmeier, @bitstorm WDYT?

**Comment by martin-g** [comment]
:+1: if everything still works !

**Comment by solomax** [comment]
@mattrpav can you check if `cglib-nodep+latest_asm` will work as expected and update your PR?

**Comment by mattrpav** [comment]
Yep, will do

**Comment by mattrpav** [comment]
My local build is hanging on wicket-core with the test below:

> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.wicket.pageStore.SerializingPageStoreTest
[INFO] Running org.apache.wicket.pageStore.FilePageStoreTest
Exception in thread "Wicket-AsyncPageStore-PageSavingThread" java.lang.NullPointerException
	at org.apache.wicket.pageStore.FilePageStore.setPageType(FilePageStore.java:352)
	at org.apache.wicket.pageStore.FilePageStore.writeFile(FilePageStore.java:223)
	at org.apache.wicket.pageStore.FilePageStore.addPersistedPage(FilePageStore.java:196)
	at org.apache.wicket.pageStore.AbstractPersistentPageStore.addPage(AbstractPersistentPageStore.java:128)
	at org.apache.wicket.pageStore.AsynchronousPageStore$PageAddingRunnable.run(AsynchronousPageStore.java:287)
	at java.base/java.lang.Thread.run(Thread.java:834)

Environment
-------------
Oracle JDK 11.2 
Mac OSX

**Comment by martin-g** [comment]
Everything looks good here!

**Pull request merged**
