### PR TITLE
Added the new KeyReplacingLocalizer

### PR DESCRIPTION
**Pull request by robsonke**
See https://issues.apache.org/jira/browse/WICKET-5847

### CODE REVIEW

**Comment by klopfdreh** [comment]
Hi @robsonke - this ticket can be closed due to the implementation of: https://issues.apache.org/jira/browse/WICKET-6193

It is a slightly different implementation as you suggested, but I think it covers your requirement.

**Comment by martin-g** [comment]
@robsonke Please close this PR because we don't have the permissions to do it ourselves! Thank you!

**Comment by martin-g** [comment]
@robsonke Ping!

**Comment by robsonke** [comment]
Oops sorry, I will

**Pull request closed without merging**
